name: build

on:
  pull_request:
  push:
    branches: 
      - master
    paths-ignore:
     - 'README.md'
  workflow_dispatch:
    inputs:
      old-build-artifacts:
        description: 'Use old artifacts?'
        required: false
        default: false
        type: boolean
  schedule:
    - cron: '0 10 * * *'
jobs:
  update-submodules:
    if: github.event_name == 'schedule'
    uses:  ./.github/workflows/update submodules.yml
  build:
    if: ${{always()}}
    needs: update-submodules
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025]
        build: [minimum-build,minimum-build-static,full-build,full-build-static]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Preparation
        shell: cmd
        run: |
          git config --global core.symlinks true
          fsutil 8dot3name set 0
          echo "Adding GNU tar to PATH"
          echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      - name: Install CUDA Toolkit and Set Paths
        shell: cmd
        run: |
          @echo off
          setlocal enabledelayedexpansion

          echo Installing CUDA Toolkit...
          rem winget の出力をリアルタイムでデバッグログへ出力
          set "winget_exit=0"
          for /f "tokens=* delims=" %%l in ('winget install --id Nvidia.CUDA -s winget -h --disable-interactivity 2^>^&1') do (
              echo ::debug::%%l
          )
          if %ERRORLEVEL% neq 0 (
              echo may CUDA installation failed with error code %ERRORLEVEL%.
          )

          rem 最新の CUDA バージョンを取得（v11 などのフォルダも考慮）
          set "CUDA_BASE=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA"
          set "latest="
          for /f "delims=" %%v in ('dir /b /ad "%CUDA_BASE%\v*" 2^>nul') do (
              set "latest=%%v"
              goto :found
          )
          dir /b /ad "%CUDA_BASE%\v*"
          echo %latest%
          echo CUDA installation failed or CUDA directory not found.
          exit /b 1

          :found
          rem 環境変数の設定
          set "CUDA_PATH=%CUDA_BASE%\%latest%"
          set "CUDA_VERSION=%latest:v=%"  rem "v12.3" -> "12.3"
          set "CUDA_VERSION_UNDERSCORE=%CUDA_VERSION:.=_%"  rem "12.3" -> "12_3"
          set "CUDA_PATH_VX_Y=CUDA_PATH_V%CUDA_VERSION_UNDERSCORE%"

          rem 環境変数を GITHUB_ENV に追加
          (
            echo CUDA_PATH=%CUDA_PATH%
            echo CUDA_PATH_V%CUDA_VERSION_UNDERSCORE%=%CUDA_PATH%
            echo CUDA_PATH_VX_Y=%CUDA_PATH_VX_Y%
          ) >> %GITHUB_ENV%

          rem CUDA のパスを追加
          (
            echo %CUDA_PATH%\bin
            echo %CUDA_PATH%\libnvvp
            echo %CUDA_PATH%\include
            echo %CUDA_PATH%\lib\x64
          ) >> %GITHUB_PATH%
          echo ::debug::%GITHUB_PATH%
          echo CUDA installation and setup completed successfully.
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          submodules: recursive
      - name: Patch bash scripts
        shell: cmd
        run: |
          call .\patch\patch_bash_scripts.bat
          xcopy settings\${{ matrix.build }}\* media-autobuild_suite\build\ /Y /I /S
          xcopy settings\common\* media-autobuild_suite\build\ /Y /I /S
      - name: Cache
        uses: actions/cache@main
        with: 
          path: media-autobuild_suite/msys64
          key: msys-2-${{ hashFiles('./media-autobuild_suite/build/media-suite_compile.sh') }}
          restore-keys: |
             msys-2-${{ hashFiles('./media-autobuild_suite/build/media-suite_compile.sh') }}
             msys-
      - name: Download artifact
        if: ${{ inputs.old-build-artifacts }}
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          name: media-autobuild_suite-${{ matrix.os }}-${{ matrix.build }}
          if_no_artifact_found: warn
      - name: extract 7z
        if: ${{ inputs.old-build-artifacts }}
        shell: cmd
        run: |
          7z.exe x ffmpeg.7z -y -o./media-autobuild_suite
          del ffmpeg.7z /Q 
      - name: run media-autobuild
        id: media-autobuild
        shell: cmd
        run: |
          call .\media-autobuild_suite\media-autobuild_suite.bat
      - name: 7z
        continue-on-error: true
        if: ${{always()}}
        shell: cmd
        run: |
          if exist ./media-autobuild_suite/build/logs.zip (7z.exe a -y -sdel ffmpeg.7z ./media-autobuild_suite/local64 ./media-autobuild_suite/build/logs.zip) else (7z.exe a -y -sdel ffmpeg.7z ./media-autobuild_suite/local64)
      - name: Upload artifacts
        if: ${{always()}}
        uses: actions/upload-artifact@v4
        with:
          name: media-autobuild_suite-${{ matrix.os }}-${{ matrix.build }}
          path: |
            ffmpeg.7z
            media-autobuild_suite/build/*_options.txt
            media-autobuild_suite/build/media-autobuild_suite.ini
